### ISSUE TITLE
Dino does not build under Cygwin

### ISSUE THREAD

**Issue by akakima** [dino-lang/dino#1]
Hi !
I downloaded Dino (zip) from dino-lang. (as of 2015-06-04)
Under Cygwin bash typed: make

msta, shilka and sprut are built ok.
and got the following error for Dino :

gcc -c -g -Ofast -flto -ffat-lto-objects -fomit-frame-pointer -DHAVE_CONFIG_H -I. -I.. -I../AMMUNITION  -I../AMMUNITION -I. -I../REGEX -DCC='"gcc"' -DDINO_VERSION=0.91 -DSTANDARD_DINO_INCLUDE_DIRECTORY=\"/usr/local/lib/dino-0.91\" -DSTANDARD_DINO_EXTERN_LIBS=\"d_ieee.a:d_ipcerr.a:d_socket.a\" -DSTANDARD_DINO_LIB_DIRECTORY=\"/usr/local/lib/dino-0.91\" -DSTANDARD_DINO_LIB_NAME=\"libdino.a\" -DNDEBUG -DNO_EXTERN_SHLIB -DIEEE_QUAD -o d_socket.o ../DINO/../DINO/d_socket.c
rm -f d_socket.a
/bin/sh -c "ar rc \$0 d_socket.o" d_socket.a
/bin/sh -c "ranlib \$0;echo \$0" d_socket.a
d_socket.a
make[1]: **\* No rule to make target 'd_mpi.a', needed by 'dino'.  Stop.
make[1]: Leaving directory '/cygdrive/c/Users/Marcus/Desktop/DINO/DINO'
Makefile:137: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by vnmakarov** [comment]
Thanks for reporting this.  I did not test it on CYGWIN yet.  I am going to this when the release will be ready (I hope sometime this year).  Meanwhile, I commit some changes which probably solve the problem.

**Comment by vnmakarov** [comment]
I've fixed this and switched DINO building system to automake and libtools.  Now Dino on master branch should be built on CYGWIN and MacOSX.  You need to install additional packages on CYGWIN (gcc/g++, bison, yacc, flex, gmp, iconv) and MacOSX (XCode and gmp).

**Comment by akakima** [comment]
Thanks !

I just downloaded the zip file.
Under the latest Cygwin (updated my Cygwin yesterday), everything builds Ok. No errors.
Using this commands:
./configure --disable-nls --disable-dependency-tracking
make
-- some packages do not build anymore after clean. But Dino is Ok
make clean 
make

Again, thanks.
