### ISSUE TITLE
Compiler warning on line 2107 in SHILKA/gen.c

### ISSUE THREAD

**Issue by teshields** [dino-lang/dino#4]
Environment:
Mac OS X El Capitan version 10.11.5 (current)
Xcode version 7.3.1 (current)

Line 2107 of 'SHILKA/gen.c' gets the following compiler warning:
gen.c:2107:42: warning: too many arguments in call to 'output_strcaseq_function'
    output_strcaseq_function (length_flag);

The signature for 'output_strcaseq_functin()' on lines 1660-1661 is:
static void
output_strcaseq_function ()

Deleting the extraneous argument 'length_flag' on line 2107 removes the compiler warning.

**Comment by vnmakarov** [comment]
Thank you.  I'll commit the patch later.

**Comment by vnmakarov** [comment]
I've committed the patch to master and dino-0.97 branch.
