### ISSUE TITLE
DINO/configure thinks Xcode's gcc supports -ffat-lto-objects, but it actually doesn't

### ISSUE THREAD

**Issue by teshields** [dino-lang/dino#6]
Environment:
Mac OS X El Capitan version 10.11.5 (current)
Xcode version 7.3.1 (current)
MacPorts version 2.3.4 (current) - provides libgmp

'DINO/configure' thinks that the Xcode installed version of gcc (clang-703.0.31) supports the '-ffat-lto-objects' compiler option, but use of that option in the build in DINO results in warnings:
   clang: warning: optimization flag '-ffat-lto-objects' is not supported

**Comment by teshields** [comment]
Note: the MacPorts version of gcc interacts with 'DINO/configure' correctly, and does support '-ffat-lto-objects'

**Comment by vnmakarov** [comment]
As I remember LLVM does not need -ffat-lto-object and ignoring it is ok for LLVM but I'll look what I can do to remove the warning.

**Comment by vnmakarov** [comment]
Dino configure script checks that the used C compiler accepts -ffat-lto-objects.  LLVM accepts it with a warning and ignores it as it is not necessary for LLVM.  Even if a compiler ignores the option, the building should work (there will be no inter-file optimizations in the worst case).

  It would be a real issue only if the configuration script did not check acceptance of -ffat-lto-objects.  But it does.  So I am closing the issue.
