### ISSUE TITLE
'ONIGURUMA/missing' doesn't implement the '--is-lightweight' option

### ISSUE THREAD

**Issue by teshields** [dino-lang/dino#7]
Environment:
Mac OS X El Capitan version 10.11.5 (current)
Xcode version 7.3.1 (current)

Running 'configure' generates a warning in ONIGURUMA:
   <path-to-ONIGURUMA>/missing: Unknown '--is-lightweight' option
   Try `<path-to-ONIGURUMA>/missing --help' for more information
   configure: WARNING: 'missing' script is too old or missing

The 'ONIGURUMA/missing' script has 'scriptversion=2006-05-10.23'; all other instances of this script in the dino distribution have 'scriptversion=2013-10-28.13' and are all identical.

Replacing the 'ONIGURUMA/missing' script with a copy of the newer version eliminates the error.

**Comment by vnmakarov** [comment]
Thank you.  ONIGURUMA did not change with user point of view  but may ONIGURUMA trunk have a new version of the script.

**Comment by vnmakarov** [comment]
I've updated version of missing script on dino-0.97 branch and updated all ONIGURUMA package to version 6.0.0 on master.
